### PR TITLE
Change activation event from onLanguage:plaintext to onLanguage:fstar \/ workspaceContains:/.fst.config.json

### PR DESCRIPTION
**Pull request by chandradeepdey**

### CODE REVIEW

**Comment by chandradeepdey** [comment]
Review request @nikswamy

**Comment by nikswamy** [comment]
hi Chandradeep, 

This makes sense it is in fact what I tried originally. But, I found that the extension was not triggering properly on F* files with this setting. Are you observing otherwise? Are you also observing the extension launch on text files that are not F*?

Thanks, 
Nik

**Comment by chandradeepdey** [comment]
Hello,

For me it correctly loads on .fst and .fsti files with this change. Normally the extension loads on VSCode launch regardless of what file or folder is open.

image

Thanks,
Chandradeep

**Comment by chandradeepdey** [comment]
Maybe this was the problem?

**Comment by nikswamy** [comment]
It seems setting activationEvents is no longer recommended for vscode engine 1.75 and beyond.

See this commit: https://github.com/FStarLang/fstar-vscode-assistant/commit/b850341d3f5fedf4405d8a5cf4c9c9956efcf106

Does it work for you?

**Comment by chandradeepdey** [comment]
Yes, the extension loads correctly with this change.

I actually saw the VSCode warning about this when modifying the file, but I thought that it might be better to not do this since 1.75 was only 2 months ago.

Should the `workspaceContains:/.fst.config.json` still be added though?

**Pull request closed without merging**
